### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Teages** [Teages/gqf#2]
## Next to do

- [ ] Improve documentation
- [ ] add cli test
- [ ] add typed test
- [ ] more test for core

## Can be parallel

- [ ] `@teages/nuxt-gqf`: nuxt module
